### ISSUE TITLE
Trying to add posts results in "Invalid cross-device link"

### ISSUE THREAD

**Issue by phil-flip** [liamw1/oxibooru#21]
Hi, I was in the process of starting up my importer script again, but ran into a general issue of not being able to add posts.

```
oxibooru-backend-1  | POST /posts/reverse-search [200 OK]
oxibooru-backend-1  | POST /posts [500 Internal Server Error]
oxibooru-backend-1  | UnknownIOError: Invalid cross-device link (os error 18)
```

I would like to mention that the data is on a NSF-Share and can be read just fine and worked fine on szuru. I upgraded to `0.3.1` but the issue was present before that.
I tried a number of things, but I have no clue what the issue could be. So I would be open to try some stuff on a call: Discord `the.phil.`

**Comment by liamw1** [comment]
I'm not sure what NSF-Share is, but judging from the error I'm assuming it's some sort of distributed storage system. It turns out that `std::fs::rename` doesn't work across devices (makes sense), so that's what could be causing the error. I've replaced all those calls with my own `move_file` function that first tries a rename and falls back to a copy/delete when moving across devices.

**Comment by phil-flip** [comment]
Sorry, ment to write NFS

**Comment by liamw1** [comment]
Well, if the migration 016 doesn't work that's an issue that should be addressed as well. Is there any useful error information it gives?

In any case, I plan to make a `0.3.2` release tonight, which doesn't include the extra migrations. So you'll be able to test-drive the file move changes soon.

**Comment by phil-flip** [comment]
```
$ docker compose up backend
[+] Running 2/2
 ✔ Container oxibooru-db-1       Running                                                                                                                                                                                                 0.0s 
 ✔ Container oxibooru-backend-1  Recreated                                                                                                                                                                                               2.1s 
Attaching to oxibooru-backend-1
oxibooru-backend-1  | Running pending migrations...
oxibooru-backend-1  | 
oxibooru-backend-1  | thread 'main' panicked at src/db.rs:57:45:
oxibooru-backend-1  | called `Result::unwrap()` on an `Err` value: QueryError(DieselMigrationName { name: "016_compress_checksums", version: MigrationVersion("016") }, DatabaseError(Unknown, "unexpected \"=\" while decoding base64 sequence"))
oxibooru-backend-1  | stack backtrace:
oxibooru-backend-1  |    0:     0x564f805550ea - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he089f96442833f67
oxibooru-backend-1  |    1:     0x564f8057e823 - core::fmt::write::h2f210ed4c94745cb
oxibooru-backend-1  |    2:     0x564f80550f23 - std::io::Write::write_fmt::h7de08171ab770fb2
oxibooru-backend-1  |    3:     0x564f80554f32 - std::sys::backtrace::BacktraceLock::print::h810fbd31421329e6
oxibooru-backend-1  |    4:     0x564f805560e0 - std::panicking::default_hook::{{closure}}::hbaad47ed9dc6356d
oxibooru-backend-1  |    5:     0x564f80555ec0 - std::panicking::default_hook::h24e207139139d40a
oxibooru-backend-1  |    6:     0x564f80556842 - std::panicking::rust_panic_with_hook::ha9131beeb2ddc506
oxibooru-backend-1  |    7:     0x564f805565ea - std::panicking::begin_panic_handler::{{closure}}::h1bba0eaeb6da506f
oxibooru-backend-1  |    8:     0x564f805555e9 - std::sys::backtrace::__rust_end_short_backtrace::h1d1ca3eade483f4c
oxibooru-backend-1  |    9:     0x564f8055627d - rust_begin_unwind
oxibooru-backend-1  |   10:     0x564f7f871440 - core::panicking::panic_fmt::h896a0727a1a943f9
oxibooru-backend-1  |   11:     0x564f7f871876 - core::result::unwrap_failed::h1b5ed8541c7bebd6
oxibooru-backend-1  |   12:     0x564f7fdb50b0 - server::db::run_migrations::h5f50d53cf2b02b20
oxibooru-backend-1  |   13:     0x564f7fa481ee - server::main::{{closure}}::h6127e0e36efdd239
oxibooru-backend-1  |   14:     0x564f7f9fd9ca - tokio::runtime::park::CachedParkThread::block_on::hdab7daade4041454
oxibooru-backend-1  |   15:     0x564f7fbd7558 - tokio::runtime::runtime::Runtime::block_on::hc70856dfb1b2de6f
oxibooru-backend-1  |   16:     0x564f7fa480a0 - server::main::hf4e45c53992911a3
oxibooru-backend-1  |   17:     0x564f7fdd7873 - std::sys::backtrace::__rust_begin_short_backtrace::hef6a81e91d02af63
oxibooru-backend-1  |   18:     0x564f7fc3f6f9 - std::rt::lang_start::{{closure}}::he2bd030894c0bb42
oxibooru-backend-1  |   19:     0x564f805498c7 - std::rt::lang_start_internal::hbb268f70c879621d
oxibooru-backend-1  |   20:     0x564f7fa48945 - main
oxibooru-backend-1  |   21:     0x7fbb443fd24a - <unknown>
oxibooru-backend-1  |   22:     0x7fbb443fd305 - __libc_start_main
oxibooru-backend-1  |   23:     0x564f7f871b41 - _start
oxibooru-backend-1  |   24:                0x0 - <unknown>
oxibooru-backend-1 exited with code 0
```

same with `unexpected \".\"` but that was because of the random checksum thing we did. there were a few that weren't converted yet. But I was not able to find any checksum(_md5) with a `=` in my DB.
I'm heading to bed for today, will check on you tomorrow.

**Comment by liamw1** [comment]
Alright, the migration issue should be fixed. 

Basically, I was assuming that the checksums were a valid base64 sequence (because that's how I was encoding them for some reason). However, you're right in pointing out that there might be a few checksums that haven't been recalculated yet, even if you were to call `recompute_post_checksums`. One way this can happen is if a row no longer corresponds to a post file on disk due to a post deletion issue. 

I've modified the migration script to fallback to converting the checksum to binary directly if it's not a valid base64 sequence. That seems to work based on some limited testing.

**Comment by phil-flip** [comment]
The migration worked out/didn't run (I didn't see it running). 
For the post-file it sets the wrong permissions tho. It works fine on the generated-thumbnails folder.

**Comment by liamw1** [comment]
What exactly is happening? Are you getting an error or do posts just appear blank?

**Comment by phil-flip** [comment]
they are blank, because the permissions are missing

![Image](https://github.com/user-attachments/assets/b647c97c-8d6b-4aa1-8eb0-ba6ab663aa60)

**Comment by liamw1** [comment]
Ok, flying a little blind here since I can't easily reproduce your issue, but I pushed a small change to how files are moved across devices.

It seems the `std::fs::copy` function doesn't preserve permissions, so I'm copying those over now. Hopefully that fixes your issue. I'm assuming this was only happening with new posts and that other posts display fine?

**Comment by phil-flip** [comment]
Unfortunately the issue still seems to be present. It's hard for me to explain the issue. But basically the server and the frontend use different user and group IDs. the server is not setting permissions for "other" to read, like it does for the thumbnails. and because they don't share the same userid and groupid, it ends up with a permission issue in the frontend.

**Comment by liamw1** [comment]
Hmmm, the post content isn't being saved differently than the thumbnails, so I'm not sure why the permissions would be different. A few questions:

1. How do you know that this is a permissions issue? Blank posts can also happen for other reasons, like if the post content doesn't exist on disk or if it's not at the expected path.
2. Are you still using a versioned instance or are you pulling the `latest` containers?
3. Are all posts missing for just newly uploaded ones?
4. Are there any errors or warnings in the server console when uploading/creating posts?

**Comment by phil-flip** [comment]
1. Yes if I change the permission, it works again.
2. I'm pulling `lastest`, because if the fix you provided
3. Newly uploaded ones, the old ones have "working" permissions (everyone is allowed to do anything, not Ideal but its only this software with access to it.)
4. There are no errors for the ones that get uploaded.

**Comment by phil-flip** [comment]
So after changing some stuff… the frontend can't open up the thumbnais either.. so it's probably an issue on my end.

**Comment by phil-flip** [comment]
Ok, so after allowing to do everything, it worked again. That's how I found out, that it needs to execute perms to I only removed write perms. so all files are now `-rwxrwxr-x+` and that works well…
but the original issue is still there: Adding new posts still seem to set the wrong permissions. It is esp weird, because the two folders are on the same NSF share.

**Comment by liamw1** [comment]
Alright, I'm now setting the permissions to 644 explicitly. Let's see if that fixes it.

**Comment by phil-flip** [comment]
Seems to have done the job. works great now
