### ISSUE TITLE
Unsuccessful HTTP response

### ISSUE THREAD

**Issue by emmanseete1996** [liamw1/oxibooru#35]
Unsuccessful HTTP response when adding 1 new tag category

<img width="816" height="523" alt="Image" src="https://github.com/user-attachments/assets/2194296a-c4db-4500-86d3-ab5e8025a11e" />

**Comment by liamw1** [comment]
Should be fixed now. The server expected the tag category order to be an integer, but for some reason the client was sending it as a string (this seems to be the only case where it does this). I added an extra cast on the client that should make this issue go away.

**Comment by emmanseete1996** [comment]
Thank you!

**Comment by emmanseete1996** [comment]
It seems the error still persist when I tried adding tag categories again.

client logs
```
172.18.0.2 -> GET /api/info HTTP/1.1 [200] - referer: https://domain.com/ **.**.**.**
172.18.0.2 -> GET /api/pool-categories HTTP/1.1 [200] - referer: https://domain.com/ **.**.**.**
172.18.0.2 -> GET /api/tag-categories HTTP/1.1 [200] - referer: https://domain.com/ **.**.**.**
172.18.0.2 -> GET /api/user/Emman?bump-login=true HTTP/1.1 [200] - referer: https://domain.com/ **.**.**.**
172.18.0.2 -> POST /api/user-token/Emman HTTP/1.1 [200] - referer: https://domain.com/ **.**.**.**
172.18.0.2 -> GET /api/tag-categories HTTP/1.1 [200] - referer: https://domain.com/ **.**.**.**
172.18.0.2 -> GET /api/pool-categories HTTP/1.1 [200] - referer: https://domain.com/ **.**.**.**
172.18.0.2 -> GET /api/tags/?limit=50&fields=names%2Csuggestions%2Cimplications%2CcreationTime%2Cusages%2Ccategory HTTP/1.1 [200] - referer: https://domain.com/tags **.**.**.**
172.18.0.2 -> PUT /api/tag-category/uncategorized HTTP/1.1 [200] - referer: https://domain.com/tag-categories **.**.**.**
172.18.0.2 -> POST /api/tag-categories HTTP/1.1 [422] - referer: https://domain.com/tag-categories **.**.**.**
172.18.0.2 -> PUT /api/tag-category/artist HTTP/1.1 [200] - referer: https://domain.com/tag-categories **.**.**.**
172.18.0.2 -> PUT /api/tag-category/meta HTTP/1.1 [200] - referer: https://domain.com/tag-categories **.**.**.**
172.18.0.2 -> PUT /api/tag-category/character HTTP/1.1 [200] - referer: https://domain.com/tag-categories **.**.**.**
172.18.0.2 -> PUT /api/tag-category/copyright HTTP/1.1 [200] - referer: https://domain.com/tag-categories **.**.**.**
```

server logs
```
INFO server::app: Oxibooru server running on 2 threads
TRACE axum::serve: connection 172.20.0.4:40190 accepted
DEBUG request{method=GET uri=/info version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=GET uri=/info version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=4 ms status=200
TRACE axum::serve: connection 172.20.0.4:40202 accepted
DEBUG request{method=GET uri=/tag-categories version=HTTP/1.0}: tower_http::trace::on_request: started processing request
TRACE axum::serve: connection 172.20.0.4:40218 accepted
DEBUG request{method=GET uri=/pool-categories version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=GET uri=/pool-categories version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=4 ms status=200
DEBUG request{method=GET uri=/tag-categories version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=5 ms status=200
TRACE axum::serve: connection 172.20.0.4:37894 accepted
DEBUG request{method=GET uri=/user/Emman?bump-login=true version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=GET uri=/user/Emman?bump-login=true version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=5 ms status=200
TRACE axum::serve: connection 172.20.0.4:37906 accepted
TRACE axum::serve: connection 172.20.0.4:37920 accepted
DEBUG request{method=POST uri=/user-token/Emman version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=POST uri=/user-token/Emman version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=4 ms status=200
TRACE axum::serve: connection 172.20.0.4:37932 accepted
DEBUG request{method=GET uri=/tag-categories version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=GET uri=/tag-categories version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=2 ms status=200
DEBUG request{method=GET uri=/pool-categories version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=GET uri=/pool-categories version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=1 ms status=200
TRACE axum::serve: connection 172.20.0.4:53014 accepted
DEBUG request{method=GET uri=/tags?limit=50&fields=names%2Csuggestions%2Cimplications%2CcreationTime%2Cusages%2Ccategory version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=GET uri=/tags?limit=50&fields=names%2Csuggestions%2Cimplications%2CcreationTime%2Cusages%2Ccategory version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=13 ms status=200
TRACE axum::serve: connection 172.20.0.4:46394 accepted
TRACE axum::serve: connection 172.20.0.4:46396 accepted
TRACE axum::serve: connection 172.20.0.4:46406 accepted
TRACE axum::serve: connection 172.20.0.4:46410 accepted
TRACE axum::serve: connection 172.20.0.4:46414 accepted
TRACE axum::serve: connection 172.20.0.4:46422 accepted
DEBUG request{method=PUT uri=/tag-category/uncategorized version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=PUT uri=/tag-category/artist version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=PUT uri=/tag-category/uncategorized version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=2 ms status=200
DEBUG request{method=POST uri=/tag-categories version=HTTP/1.0}: tower_http::trace::on_request: started processing request
TRACE request{method=POST uri=/tag-categories version=HTTP/1.0}: axum::rejection: rejecting request status=422 body="Failed to deserialize the JSON body into the target type: order: invalid type: string \"5\", expected i32 at line 1 column 47" rejection_type="axum::extract::rejection::JsonDataError"
DEBUG request{method=POST uri=/tag-categories version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=0 ms status=422
DEBUG request{method=PUT uri=/tag-category/artist version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=2 ms status=200
DEBUG request{method=PUT uri=/tag-category/meta version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=PUT uri=/tag-category/meta version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=1 ms status=200
DEBUG request{method=PUT uri=/tag-category/character version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=PUT uri=/tag-category/copyright version=HTTP/1.0}: tower_http::trace::on_request: started processing request
DEBUG request{method=PUT uri=/tag-category/character version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=1 ms status=200
DEBUG request{method=PUT uri=/tag-category/copyright version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=1 ms status=200
```

**Comment by emmanseete1996** [comment]
still the same error response i am getting 

<img width="743" height="574" alt="Image" src="https://github.com/user-attachments/assets/bbb7bbc0-e408-4ad7-83e5-99d4380655d5" />

**Comment by emmanseete1996** [comment]
Refer to 6112edc - Fixed error when attempting tag category creation.
