### ISSUE TITLE
API Incompatibilities/Breaking Changes

### ISSUE THREAD

**Issue by tcaivano** [liamw1/oxibooru#8]
I'm attempting to move my szuru instance to an oxibooru instance, and I'm unable to use the conversion script (getting errors on that but not what this issue is for). I'm attempting to use API scripts that work perfectly well with other szurubooru instances but are throwing API errors when run against oxi's API.

Szuru Chrome: https://github.com/neobooru/SzuruChrome/ - throws an error on Test Connection

![Image](https://github.com/user-attachments/assets/8f99ef2f-92ad-4f31-8c2c-5f0e34790233)

I have some unreleased custom scripts, and this one 1) downloads a post from szuru instance #1, 2) prepares the data into the API specified format, and 3) uploads, tags, and adds all metadata to a new post in szuru instance #2. 

```
{'metadata': ('metadata', '{"tags": ["artist", ...], "safety": "unsafe", "source": "<url>"}', 'multipart/form-data'), 'content': ('1_beab17a1cf6e1ba6.jpg', <_io.BufferedReader name='downloads/1_beab17a1cf6e1ba6.jpg'>, 'multipart/form-data')}

400 Client Error: Bad Request for url: http://192.168.50.19:3623/api/posts/
Traceback (most recent call last):
...
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.50.19:3623/api/posts/
```

Are these errors expected?

**Comment by liamw1** [comment]
Are you using one of the releases or are you just using the master branch? If you're on master, have you pulled the latest images recently?

**Comment by liamw1** [comment]
Hmm, the first error is pretty strange and I can't seem to reproduce it. I can establish a test connection with SzuruChrome just fine. For a sanity check, is the authentication token you're using a [valid v4 UUID](https://www.freecodeformat.com/validate-uuid-guid.php)?

For both of these errors, is there any additional information in the server console when the they occur?

**Comment by tcaivano** [comment]
I ended up updating the extension to the latest version and the issue went away - maybe an issue with how the auth token was being stored on the extension?

Going past that, I'm now seeing these errors on the extension:

![Image](https://github.com/user-attachments/assets/e3d2dae2-b961-460c-97f0-e23e1dc51bf4)

Unfortunately no hints in the console.

**Comment by Krazer89** [comment]
Here is the Docker output I get for the same errors as https://github.com/liamw1/oxibooru/issues/8#issuecomment-2632900197
```
server-1  | POST /uploads [400 Bad Request]
server-1  | BadExtension:  is not a supported file extension
client-1  | 192.168.0.2 -> POST /api/uploads HTTP/1.1 [400] - referer: - -
client-1  | 2025/02/04 09:04:55 [warn] 10#10: *1 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000003, client: 192.168.0.2, server: , request: "POST /api/uploads HTTP/1.1", host: "192.168.0.1:1239"
server-1  | BadExtension:  is not a supported file extension
server-1  | POST /uploads [400 Bad Request]
client-1  | 192.168.0.2 -> POST /api/uploads HTTP/1.1 [400] - referer: - -
```  
<br>
This happens because the server is expecting the multipart form data to include a filename with extension

https://github.com/liamw1/oxibooru/blob/fda1a965c2adbb6e85ed91dd884e524e66b10ed3/server/src/content/upload.rs#L137C1-L144

SzuruChrome sends a multipart form with the filename "blob" like so:

```
------WebKitFormBoundaryY6aA3qa5gfLFufOS
Content-Disposition: form-data; name="content"; filename="blob"
Content-Type: image/png
```

As a quick test I bodged the server to get the MIME type from Content-Type instead, this makes the find similar (reverse search) work, however uploading/creating a new post still fails.
![Image](https://github.com/user-attachments/assets/49611187-17e6-4a26-8504-884905dc658e)

```
server-1  | POST /uploads [200 OK]
client-1  | 169.254.2.65 -> POST /api/uploads HTTP/1.1 [200] - referer: - 192.168.0.254
server-1  | POST /posts [400 Bad Request]
server-1  | No endpoint for request!
client-1  | 169.254.2.65 -> POST /api/posts HTTP/1.1 [400] - referer: - 192.168.0.254
```

<br>

### Find similar (reverse search)
![Empty booru](https://github.com/user-attachments/assets/3fe85230-894e-41dd-85de-c0fb09d8f95c)

![Manual upload](https://github.com/user-attachments/assets/8044bc12-662c-40f3-9b3a-64af6782b558)


Merging tags, safety, and source to an existing post works fine.
![Image](https://github.com/user-attachments/assets/6ead95c0-f2ab-4893-8be2-3c0a5ce44fec)

**Comment by liamw1** [comment]
Alright, these issues should be fixed now.

Multipart uploads now accept filenames with no extension, as long as the MIME type can be inferred from the content-type field. It turns out my struct for serializing a post creation body was missing a "notes" field, which was causing an error when SzuruChrome tried using a body with an empty "notes" field.

Also, fetching images via a URL isn't implemented yet in Oxibooru, so make sure you're always uploading by content for now or else you'll get an error.

**Comment by tcaivano** [comment]
Can confirm that I'm seeing SzuruChrome working as expected now, thanks!

Unfortunately, still getting the same Bad Request error using my API scripts.
I was able to get into the containers and get some logs:
```
POST /posts/ [400 Bad Request]
ContentTypeMismatch: File of type image/jpeg did not match request with content-type application/octet-stream
```
or changing my script to multipart/form-data:
```
POST /posts/ [400 Bad Request]
ContentTypeMismatch: File of type image/jpeg did not match request with content-type multipart/form-data
```
but now I'm getting this mysterious error:
```
POST /posts/ [400 Bad Request]
SerdeJsonData: missing field `contentToken` at line 1 column 940
```
An observation - The szuru API reference notes that image uploads should be done with multipart/form-data, although application/octet-stream has worked without issue. Not sure if this is a szuru bug or intended behavior.

**Comment by tcaivano** [comment]
Also to add - seems like there's a similar issue with the tags API

```
DELETE /tag/white_background [400 Bad Request]
GET /tags/ [200 OK]
```

**Comment by liamw1** [comment]
The content-type of the upload should ideally be something like `image/png`, but I'll add in an escape hatch in the form of `application/octet-stream` if you want the MIME type to be inferred from the extension.

For the tag API issue, what's an example of the request body you're sending along with it?

**Comment by tcaivano** [comment]
I'm sending this for the delete verb:

```
headers = {
        'Authorization': f'Token {TOKEN}',
        'Accept': 'application/json'
    }
    
    params = {
        'version': version
    }
    
    response = requests.delete(f'{BASE_URL}/tag/{tag}', params=params, headers=headers)
```

**Comment by liamw1** [comment]
Alright, I've just pushed some more fixes.

The `contentToken` error was caused by an oversight in how I implemented multipart post creation requests.

The `ContentTypeMismatch` errors should go away now if you set the content-type to `application/octet-stream` for multipart requests.

For the tag deletion error, it looks like the `version` is being sent as a parameter, but it needs to be sent as a JSON body.

**Comment by liamw1** [comment]
As of 0.3.0, multipart uploads and url-based uploads have implemented. If anyone is still having similar problems, feel free to open this issue again.
